"""astro-context: Context engineering toolkit for AI applications.

Agent:
    Agent, AgentTool, tool, memory_tools, rag_tools

Core Pipeline:
    ContextPipeline, ContextResult, PipelineStep, PipelineCallback,
    PipelineDiagnostics, StepDiagnostic, PipelineExecutionError,
    retriever_step, filter_step, postprocessor_step, reranker_step,
    async_retriever_step, async_postprocessor_step, async_reranker_step,
    auto_promotion_step, graph_retrieval_step, create_eviction_promoter,
    query_transform_step

Memory Management:
    MemoryManager, SlidingWindowMemory, SummaryBufferMemory, SimpleGraphMemory,
    MemoryGarbageCollector, GCStats, MemoryCallback, CallbackExtractor,
    MemoryContextEnricher, ContextQueryEnricher,
    FIFOEviction, ImportanceEviction, PairedEviction,
    SimilarityConsolidator, ExponentialRecencyScorer, LinearRecencyScorer,
    EbbinghausDecay, LinearDecay

Retrieval:
    DenseRetriever, SparseRetriever, HybridRetriever, ScoreReranker,
    CrossEncoderReranker, CohereReranker, FlashRankReranker,
    RoundRobinReranker, RerankerPipeline,
    ScoredMemoryRetriever, MemoryRetrieverAdapter

Formatting:
    AnthropicFormatter, OpenAIFormatter, GenericTextFormatter, BaseFormatter

Query Transformation:
    HyDETransformer, MultiQueryTransformer, DecompositionTransformer,
    StepBackTransformer, QueryTransformPipeline, query_transform_step

Evaluation:
    RetrievalMetrics, RAGMetrics, EvaluationResult,
    RetrievalMetricsCalculator, LLMRAGEvaluator, PipelineEvaluator

Multi-modal:
    ModalityType, MultiModalContent, MultiModalItem, MultiModalConverter,
    CompositeEncoder, ImageDescriptionEncoder, TableEncoder, TextEncoder,
    MarkdownTableParser, HTMLTableParser,
    ModalityEncoder, TableExtractor

Observability:
    Tracer, TracingCallback, Span, SpanKind, TraceRecord, MetricPoint,
    ConsoleSpanExporter, InMemorySpanExporter, FileSpanExporter,
    InMemoryMetricsCollector, LoggingMetricsCollector

Protocols (extension points):
    Retriever, AsyncRetriever, PostProcessor, AsyncPostProcessor,
    QueryTransformer, AsyncQueryTransformer,
    Reranker, AsyncReranker,
    Tokenizer, Formatter, QueryEnricher, MemoryQueryEnricher, RecencyScorer,
    EvictionPolicy, CompactionStrategy, AsyncCompactionStrategy,
    MemoryExtractor, AsyncMemoryExtractor, MemoryConsolidator, MemoryDecay,
    ContextStore, DocumentStore, VectorStore, MemoryEntryStore,
    GarbageCollectableStore, ConversationMemory, MemoryProvider,
    RetrievalEvaluator, RAGEvaluator,
    ModalityEncoder, TableExtractor,
    SpanExporter, MetricsCollector

Storage:
    InMemoryContextStore, InMemoryDocumentStore, InMemoryVectorStore,
    InMemoryEntryStore, JsonFileMemoryStore

Models & Types:
    ContextItem, ContextWindow, QueryBundle, TokenBudget, BudgetAllocation,
    ConversationTurn, MemoryEntry, MemoryType, MemoryOperation,
    SourceType, OverflowStrategy, Role,
    StreamDelta, StreamResult, StreamUsage,
    default_chat_budget, default_rag_budget, default_agent_budget

Ingestion:
    DocumentIngester, FixedSizeChunker, RecursiveCharacterChunker,
    SentenceChunker, PlainTextParser, MarkdownParser, HTMLParser, PDFParser,
    MetadataEnricher, generate_doc_id, generate_chunk_id, extract_chunk_metadata

Exceptions:
    AstroContextError, FormatterError, IngestionError, RetrieverError,
    StorageError, TokenBudgetExceededError

Tokens:
    TiktokenCounter
"""

from importlib.metadata import PackageNotFoundError, version

from astro_context.agent import (
    Agent,
    AgentTool,
    Skill,
    SkillRegistry,
    memory_skill,
    memory_tools,
    rag_skill,
    rag_tools,
    tool,
)
from astro_context.evaluation import (
    EvaluationResult,
    LLMRAGEvaluator,
    PipelineEvaluator,
    RAGMetrics,
    RetrievalMetrics,
    RetrievalMetricsCalculator,
)
from astro_context.exceptions import (
    AstroContextError,
    FormatterError,
    IngestionError,
    PipelineExecutionError,
    RetrieverError,
    StorageError,
    TokenBudgetExceededError,
)
from astro_context.formatters import (
    AnthropicFormatter,
    BaseFormatter,
    Formatter,
    GenericTextFormatter,
    OpenAIFormatter,
)
from astro_context.ingestion import (
    DocumentIngester,
    FixedSizeChunker,
    HTMLParser,
    MarkdownParser,
    MetadataEnricher,
    PDFParser,
    PlainTextParser,
    RecursiveCharacterChunker,
    SentenceChunker,
    extract_chunk_metadata,
    generate_chunk_id,
    generate_doc_id,
)
from astro_context.memory import (
    CallbackExtractor,
    EbbinghausDecay,
    ExponentialRecencyScorer,
    FIFOEviction,
    GCStats,
    ImportanceEviction,
    LinearDecay,
    LinearRecencyScorer,
    MemoryCallback,
    MemoryGarbageCollector,
    MemoryManager,
    PairedEviction,
    SimilarityConsolidator,
    SimpleGraphMemory,
    SlidingWindowMemory,
    SummaryBufferMemory,
)
from astro_context.models import (
    BudgetAllocation,
    ContextItem,
    ContextResult,
    ContextWindow,
    ConversationTurn,
    MemoryEntry,
    MemoryType,
    OverflowStrategy,
    PipelineDiagnostics,
    QueryBundle,
    Role,
    SourceType,
    StepDiagnostic,
    StreamDelta,
    StreamResult,
    StreamUsage,
    TokenBudget,
    default_agent_budget,
    default_chat_budget,
    default_rag_budget,
)
from astro_context.multimodal import (
    CompositeEncoder,
    HTMLTableParser,
    ImageDescriptionEncoder,
    MarkdownTableParser,
    ModalityType,
    MultiModalContent,
    MultiModalConverter,
    MultiModalItem,
    TableEncoder,
    TextEncoder,
)
from astro_context.observability import (
    ConsoleSpanExporter,
    FileSpanExporter,
    InMemoryMetricsCollector,
    InMemorySpanExporter,
    LoggingMetricsCollector,
    MetricPoint,
    Span,
    SpanKind,
    Tracer,
    TraceRecord,
    TracingCallback,
)
from astro_context.pipeline import (
    ContextPipeline,
    ContextQueryEnricher,
    MemoryContextEnricher,
    PipelineCallback,
    PipelineStep,
    async_postprocessor_step,
    async_reranker_step,
    async_retriever_step,
    auto_promotion_step,
    create_eviction_promoter,
    filter_step,
    graph_retrieval_step,
    postprocessor_step,
    query_transform_step,
    reranker_step,
    retriever_step,
)
from astro_context.protocols import (
    AsyncCompactionStrategy,
    AsyncMemoryExtractor,
    AsyncPostProcessor,
    AsyncQueryTransformer,
    AsyncReranker,
    AsyncRetriever,
    Chunker,
    CompactionStrategy,
    ContextStore,
    ConversationMemory,
    DocumentParser,
    DocumentStore,
    EvictionPolicy,
    GarbageCollectableStore,
    MemoryConsolidator,
    MemoryDecay,
    MemoryEntryStore,
    MemoryExtractor,
    MemoryOperation,
    MemoryProvider,
    MemoryQueryEnricher,
    MetricsCollector,
    ModalityEncoder,
    PostProcessor,
    QueryEnricher,
    QueryTransformer,
    RAGEvaluator,
    RecencyScorer,
    Reranker,
    RetrievalEvaluator,
    Retriever,
    SpanExporter,
    TableExtractor,
    Tokenizer,
    VectorStore,
)
from astro_context.query import (
    DecompositionTransformer,
    HyDETransformer,
    MultiQueryTransformer,
    QueryTransformPipeline,
    StepBackTransformer,
)
from astro_context.retrieval import (
    CohereReranker,
    CrossEncoderReranker,
    DenseRetriever,
    FlashRankReranker,
    HybridRetriever,
    MemoryRetrieverAdapter,
    RerankerPipeline,
    RoundRobinReranker,
    ScoredMemoryRetriever,
    ScoreReranker,
    SparseRetriever,
)
from astro_context.storage import (
    InMemoryContextStore,
    InMemoryDocumentStore,
    InMemoryEntryStore,
    InMemoryVectorStore,
    JsonFileMemoryStore,
)
from astro_context.tokens import TiktokenCounter

try:
    __version__ = version("astro-context")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"

__all__ = [
    "Agent",
    "AgentTool",
    "AnthropicFormatter",
    "AstroContextError",
    "AsyncCompactionStrategy",
    "AsyncMemoryExtractor",
    "AsyncPostProcessor",
    "AsyncQueryTransformer",
    "AsyncReranker",
    "AsyncRetriever",
    "BaseFormatter",
    "BudgetAllocation",
    "CallbackExtractor",
    "Chunker",
    "CohereReranker",
    "CompactionStrategy",
    "CompositeEncoder",
    "ConsoleSpanExporter",
    "ContextItem",
    "ContextPipeline",
    "ContextQueryEnricher",
    "ContextResult",
    "ContextStore",
    "ContextWindow",
    "ConversationMemory",
    "ConversationTurn",
    "CrossEncoderReranker",
    "DecompositionTransformer",
    "DenseRetriever",
    "DocumentIngester",
    "DocumentParser",
    "DocumentStore",
    "EbbinghausDecay",
    "EvaluationResult",
    "EvictionPolicy",
    "ExponentialRecencyScorer",
    "FIFOEviction",
    "FileSpanExporter",
    "FixedSizeChunker",
    "FlashRankReranker",
    "Formatter",
    "FormatterError",
    "GCStats",
    "GarbageCollectableStore",
    "GenericTextFormatter",
    "HTMLParser",
    "HTMLTableParser",
    "HyDETransformer",
    "HybridRetriever",
    "ImageDescriptionEncoder",
    "ImportanceEviction",
    "InMemoryContextStore",
    "InMemoryDocumentStore",
    "InMemoryEntryStore",
    "InMemoryMetricsCollector",
    "InMemorySpanExporter",
    "InMemoryVectorStore",
    "IngestionError",
    "JsonFileMemoryStore",
    "LLMRAGEvaluator",
    "LinearDecay",
    "LinearRecencyScorer",
    "LoggingMetricsCollector",
    "MarkdownParser",
    "MarkdownTableParser",
    "MemoryCallback",
    "MemoryConsolidator",
    "MemoryContextEnricher",
    "MemoryDecay",
    "MemoryEntry",
    "MemoryEntryStore",
    "MemoryExtractor",
    "MemoryGarbageCollector",
    "MemoryManager",
    "MemoryOperation",
    "MemoryProvider",
    "MemoryQueryEnricher",
    "MemoryRetrieverAdapter",
    "MemoryType",
    "MetadataEnricher",
    "MetricPoint",
    "MetricsCollector",
    "ModalityEncoder",
    "ModalityType",
    "MultiModalContent",
    "MultiModalConverter",
    "MultiModalItem",
    "MultiQueryTransformer",
    "OpenAIFormatter",
    "OverflowStrategy",
    "PDFParser",
    "PairedEviction",
    "PipelineCallback",
    "PipelineDiagnostics",
    "PipelineEvaluator",
    "PipelineExecutionError",
    "PipelineStep",
    "PlainTextParser",
    "PostProcessor",
    "QueryBundle",
    "QueryEnricher",
    "QueryTransformPipeline",
    "QueryTransformer",
    "RAGEvaluator",
    "RAGMetrics",
    "RecencyScorer",
    "RecursiveCharacterChunker",
    "Reranker",
    "RerankerPipeline",
    "RetrievalEvaluator",
    "RetrievalMetrics",
    "RetrievalMetricsCalculator",
    "Retriever",
    "RetrieverError",
    "Role",
    "RoundRobinReranker",
    "ScoreReranker",
    "ScoredMemoryRetriever",
    "SentenceChunker",
    "SimilarityConsolidator",
    "SimpleGraphMemory",
    "Skill",
    "SkillRegistry",
    "SlidingWindowMemory",
    "SourceType",
    "Span",
    "SpanExporter",
    "SpanKind",
    "SparseRetriever",
    "StepBackTransformer",
    "StepDiagnostic",
    "StorageError",
    "StreamDelta",
    "StreamResult",
    "StreamUsage",
    "SummaryBufferMemory",
    "TableEncoder",
    "TableExtractor",
    "TextEncoder",
    "TiktokenCounter",
    "TokenBudget",
    "TokenBudgetExceededError",
    "Tokenizer",
    "TraceRecord",
    "Tracer",
    "TracingCallback",
    "VectorStore",
    "async_postprocessor_step",
    "async_reranker_step",
    "async_retriever_step",
    "auto_promotion_step",
    "create_eviction_promoter",
    "default_agent_budget",
    "default_chat_budget",
    "default_rag_budget",
    "extract_chunk_metadata",
    "filter_step",
    "generate_chunk_id",
    "generate_doc_id",
    "graph_retrieval_step",
    "memory_skill",
    "memory_tools",
    "postprocessor_step",
    "query_transform_step",
    "rag_skill",
    "rag_tools",
    "reranker_step",
    "retriever_step",
    "tool",
]
