"""anchor: Context engineering toolkit for AI applications.

Agent:
    Agent, AgentTool, tool, memory_tools, rag_tools

Core Pipeline:
    ContextPipeline, ContextResult, PipelineStep, PipelineCallback,
    PipelineDiagnostics, StepDiagnostic, PipelineExecutionError,
    retriever_step, filter_step, postprocessor_step, reranker_step,
    async_retriever_step, async_postprocessor_step, async_reranker_step,
    auto_promotion_step, graph_retrieval_step, create_eviction_promoter,
    query_transform_step, classified_retriever_step

Caching:
    CacheBackend, InMemoryCacheBackend

Memory Management:
    MemoryManager, SlidingWindowMemory, SummaryBufferMemory, ProgressiveSummarizationMemory,
    TierCompactor, SimpleGraphMemory,
    MemoryGarbageCollector, GCStats, MemoryCallback, CallbackExtractor,
    MemoryContextEnricher, ContextQueryEnricher,
    FIFOEviction, ImportanceEviction, PairedEviction,
    SimilarityConsolidator, ExponentialRecencyScorer, LinearRecencyScorer,
    EbbinghausDecay, LinearDecay

Retrieval:
    DenseRetriever, SparseRetriever, HybridRetriever, ScoreReranker,
    CrossEncoderReranker, CohereReranker, FlashRankReranker,
    RoundRobinReranker, RerankerPipeline,
    ScoredMemoryRetriever, MemoryRetrieverAdapter, rrf_fuse,
    CallbackRouter, KeywordRouter, MetadataRouter, RoutedRetriever

Formatting:
    AnthropicFormatter, OpenAIFormatter, GenericTextFormatter, BaseFormatter

Query Transformation:
    HyDETransformer, MultiQueryTransformer, DecompositionTransformer,
    StepBackTransformer, QueryTransformPipeline, query_transform_step

Evaluation:
    RetrievalMetrics, RAGMetrics, EvaluationResult,
    RetrievalMetricsCalculator, LLMRAGEvaluator, PipelineEvaluator,
    EvaluationSample, EvaluationDataset, AggregatedMetrics, BatchEvaluator

Multi-modal:
    ModalityType, MultiModalContent, MultiModalItem, MultiModalConverter,
    CompositeEncoder, ImageDescriptionEncoder, TableEncoder, TextEncoder,
    MarkdownTableParser, HTMLTableParser,
    ModalityEncoder, TableExtractor

Observability:
    Tracer, TracingCallback, Span, SpanKind, TraceRecord, MetricPoint,
    ConsoleSpanExporter, InMemorySpanExporter, FileSpanExporter,
    OTLPSpanExporter, OTLPMetricsExporter,
    InMemoryMetricsCollector, LoggingMetricsCollector,
    CostEntry, CostSummary, CostTracker, CostTrackingCallback

Protocols (extension points):
    Retriever, AsyncRetriever, PostProcessor, AsyncPostProcessor,
    QueryTransformer, AsyncQueryTransformer,
    Reranker, AsyncReranker,
    Tokenizer, Formatter, QueryEnricher, MemoryQueryEnricher, RecencyScorer,
    EvictionPolicy, CompactionStrategy, AsyncCompactionStrategy,
    MemoryExtractor, AsyncMemoryExtractor, MemoryConsolidator, MemoryDecay,
    ContextStore, DocumentStore, VectorStore, MemoryEntryStore,
    GarbageCollectableStore, ConversationMemory, MemoryProvider,
    RetrievalEvaluator, RAGEvaluator,
    ModalityEncoder, TableExtractor,
    SpanExporter, MetricsCollector,
    QueryRouter, CacheBackend

Storage:
    InMemoryContextStore, InMemoryDocumentStore, InMemoryVectorStore,
    InMemoryEntryStore, JsonFileMemoryStore

Models & Types:
    ContextItem, ContextWindow, QueryBundle, TokenBudget, BudgetAllocation,
    ConversationTurn, MemoryEntry, MemoryType, MemoryOperation,
    SourceType, OverflowStrategy, Role,
    StreamDelta, StreamResult, StreamUsage,
    default_chat_budget, default_rag_budget, default_agent_budget

Ingestion:
    DocumentIngester, FixedSizeChunker, RecursiveCharacterChunker,
    SemanticChunker, SentenceChunker, ParentChildChunker, ParentExpander,
    PlainTextParser, MarkdownParser, HTMLParser, PDFParser,
    MetadataEnricher, generate_doc_id, generate_chunk_id, extract_chunk_metadata

Exceptions:
    AstroContextError, FormatterError, IngestionError, RetrieverError,
    StorageError, TokenBudgetExceededError

Tokens:
    TiktokenCounter
"""

from importlib.metadata import PackageNotFoundError, version

from anchor.agent import (
    Agent,
    AgentTool,
    Skill,
    SkillRegistry,
    memory_skill,
    memory_tools,
    rag_skill,
    rag_tools,
    tool,
)
from anchor.cache import InMemoryCacheBackend
from anchor.evaluation import (
    ABTestResult,
    ABTestRunner,
    AggregatedMetrics,
    BatchEvaluator,
    EvaluationDataset,
    EvaluationResult,
    EvaluationSample,
    HumanEvaluationCollector,
    HumanJudgment,
    LLMRAGEvaluator,
    PipelineEvaluator,
    RAGMetrics,
    RetrievalMetrics,
    RetrievalMetricsCalculator,
)
from anchor.exceptions import (
    AstroContextError,
    FormatterError,
    IngestionError,
    PipelineExecutionError,
    RetrieverError,
    StorageError,
    TokenBudgetExceededError,
)
from anchor.formatters import (
    AnthropicFormatter,
    BaseFormatter,
    Formatter,
    GenericTextFormatter,
    OpenAIFormatter,
)
from anchor.ingestion import (
    CodeChunker,
    DocumentIngester,
    FixedSizeChunker,
    HTMLParser,
    MarkdownParser,
    MetadataEnricher,
    ParentChildChunker,
    ParentExpander,
    PDFParser,
    PlainTextParser,
    RecursiveCharacterChunker,
    SemanticChunker,
    SentenceChunker,
    TableAwareChunker,
    extract_chunk_metadata,
    generate_chunk_id,
    generate_doc_id,
)
from anchor.memory import (
    CallbackExtractor,
    EbbinghausDecay,
    ExponentialRecencyScorer,
    FIFOEviction,
    GCStats,
    ImportanceEviction,
    LinearDecay,
    LinearRecencyScorer,
    MemoryCallback,
    MemoryGarbageCollector,
    MemoryManager,
    PairedEviction,
    ProgressiveSummarizationMemory,
    SimilarityConsolidator,
    SimpleGraphMemory,
    SlidingWindowMemory,
    SummaryBufferMemory,
    TierCompactor,
)
from anchor.models import (
    BudgetAllocation,
    ContextItem,
    ContextResult,
    ContextWindow,
    ConversationTurn,
    MemoryEntry,
    MemoryType,
    OverflowStrategy,
    PipelineDiagnostics,
    QueryBundle,
    Role,
    SourceType,
    StepDiagnostic,
    StreamDelta,
    StreamResult,
    StreamUsage,
    TokenBudget,
    default_agent_budget,
    default_chat_budget,
    default_rag_budget,
)
from anchor.multimodal import (
    CompositeEncoder,
    HTMLTableParser,
    ImageDescriptionEncoder,
    MarkdownTableParser,
    ModalityType,
    MultiModalContent,
    MultiModalConverter,
    MultiModalItem,
    TableEncoder,
    TextEncoder,
)
from anchor.observability import (
    ConsoleSpanExporter,
    CostEntry,
    CostSummary,
    CostTracker,
    CostTrackingCallback,
    FileSpanExporter,
    InMemoryMetricsCollector,
    InMemorySpanExporter,
    LoggingMetricsCollector,
    MetricPoint,
    OTLPMetricsExporter,
    OTLPSpanExporter,
    Span,
    SpanKind,
    Tracer,
    TraceRecord,
    TracingCallback,
)
from anchor.pipeline import (
    ContextPipeline,
    ContextQueryEnricher,
    MemoryContextEnricher,
    PipelineCallback,
    PipelineStep,
    async_postprocessor_step,
    async_reranker_step,
    async_retriever_step,
    auto_promotion_step,
    classified_retriever_step,
    create_eviction_promoter,
    filter_step,
    graph_retrieval_step,
    postprocessor_step,
    query_transform_step,
    reranker_step,
    retriever_step,
)
from anchor.protocols import (
    AsyncCompactionStrategy,
    AsyncMemoryExtractor,
    AsyncPostProcessor,
    AsyncQueryTransformer,
    AsyncReranker,
    AsyncRetriever,
    CacheBackend,
    Chunker,
    CompactionStrategy,
    ContextStore,
    ConversationMemory,
    DocumentParser,
    DocumentStore,
    EvictionPolicy,
    GarbageCollectableStore,
    HumanEvaluator,
    MemoryConsolidator,
    MemoryDecay,
    MemoryEntryStore,
    MemoryExtractor,
    MemoryOperation,
    MemoryProvider,
    MemoryQueryEnricher,
    MetricsCollector,
    ModalityEncoder,
    PostProcessor,
    QueryClassifier,
    QueryEnricher,
    QueryRouter,
    QueryTransformer,
    RAGEvaluator,
    RecencyScorer,
    Reranker,
    RetrievalEvaluator,
    Retriever,
    SpanExporter,
    TableExtractor,
    Tokenizer,
    TokenLevelEncoder,
    VectorStore,
)
from anchor.query import (
    CallbackClassifier,
    ContextualQueryTransformer,
    ConversationRewriter,
    DecompositionTransformer,
    EmbeddingClassifier,
    HyDETransformer,
    KeywordClassifier,
    MultiQueryTransformer,
    QueryTransformPipeline,
    StepBackTransformer,
)
from anchor.retrieval import (
    AsyncCohereReranker,
    AsyncCrossEncoderReranker,
    AsyncDenseRetriever,
    AsyncHybridRetriever,
    CallbackRouter,
    CohereReranker,
    CrossEncoderReranker,
    CrossModalEncoder,
    DenseRetriever,
    FlashRankReranker,
    HybridRetriever,
    KeywordRouter,
    LateInteractionRetriever,
    LateInteractionScorer,
    MaxSimScorer,
    MemoryRetrieverAdapter,
    MetadataRouter,
    RerankerPipeline,
    RoundRobinReranker,
    RoutedRetriever,
    ScoredMemoryRetriever,
    ScoreReranker,
    SharedSpaceRetriever,
    SparseRetriever,
    rrf_fuse,
)
from anchor.storage import (
    InMemoryContextStore,
    InMemoryDocumentStore,
    InMemoryEntryStore,
    InMemoryVectorStore,
    JsonFileMemoryStore,
)
from anchor.tokens import TiktokenCounter
from anchor.llm import (
    AuthenticationError,
    BaseLLMProvider,
    ContentBlock,
    ContentFilterError,
    FallbackProvider,
    LLMProvider,
    LLMResponse,
    MODEL_PRICING,
    Message,
    ModelNotFoundError,
    ProviderError,
    ProviderNotInstalledError,
    RateLimitError,
    ServerError,
    StopReason,
    StreamChunk,
    TimeoutError,
    ToolCall,
    ToolCallDelta,
    ToolResult,
    ToolSchema,
    Usage,
    calculate_cost,
    create_provider,
    register_provider,
)  # Note: Role is intentionally NOT imported here — it comes from anchor.models above

try:
    __version__ = version("astro-anchor")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"

__all__ = [
    "ABTestResult",
    "ABTestRunner",
    "Agent",
    "AgentTool",
    "AuthenticationError",
    "AggregatedMetrics",
    "AnthropicFormatter",
    "AstroContextError",
    "AsyncCohereReranker",
    "AsyncCompactionStrategy",
    "AsyncCrossEncoderReranker",
    "AsyncDenseRetriever",
    "AsyncHybridRetriever",
    "AsyncMemoryExtractor",
    "AsyncPostProcessor",
    "AsyncQueryTransformer",
    "AsyncReranker",
    "AsyncRetriever",
    "BaseFormatter",
    "BaseLLMProvider",
    "BatchEvaluator",
    "BudgetAllocation",
    "CacheBackend",
    "CallbackClassifier",
    "CallbackExtractor",
    "CallbackRouter",
    "Chunker",
    "CodeChunker",
    "CohereReranker",
    "CompactionStrategy",
    "CompositeEncoder",
    "ConsoleSpanExporter",
    "ContentBlock",
    "ContentFilterError",
    "ContextItem",
    "ContextPipeline",
    "ContextQueryEnricher",
    "ContextResult",
    "ContextStore",
    "ContextWindow",
    "ContextualQueryTransformer",
    "ConversationMemory",
    "ConversationRewriter",
    "ConversationTurn",
    "CostEntry",
    "CostSummary",
    "CostTracker",
    "CostTrackingCallback",
    "CrossEncoderReranker",
    "CrossModalEncoder",
    "DecompositionTransformer",
    "DenseRetriever",
    "DocumentIngester",
    "DocumentParser",
    "DocumentStore",
    "EbbinghausDecay",
    "EmbeddingClassifier",
    "EvaluationDataset",
    "EvaluationResult",
    "EvaluationSample",
    "EvictionPolicy",
    "ExponentialRecencyScorer",
    "FIFOEviction",
    "FallbackProvider",
    "FileSpanExporter",
    "FixedSizeChunker",
    "FlashRankReranker",
    "Formatter",
    "FormatterError",
    "GCStats",
    "GarbageCollectableStore",
    "GenericTextFormatter",
    "HTMLParser",
    "HTMLTableParser",
    "HumanEvaluationCollector",
    "HumanEvaluator",
    "HumanJudgment",
    "HyDETransformer",
    "HybridRetriever",
    "ImageDescriptionEncoder",
    "ImportanceEviction",
    "InMemoryCacheBackend",
    "InMemoryContextStore",
    "InMemoryDocumentStore",
    "InMemoryEntryStore",
    "InMemoryMetricsCollector",
    "InMemorySpanExporter",
    "InMemoryVectorStore",
    "IngestionError",
    "JsonFileMemoryStore",
    "KeywordClassifier",
    "KeywordRouter",
    "LLMProvider",
    "LLMRAGEvaluator",
    "LLMResponse",
    "LateInteractionRetriever",
    "LateInteractionScorer",
    "LinearDecay",
    "LinearRecencyScorer",
    "LoggingMetricsCollector",
    "MarkdownParser",
    "MarkdownTableParser",
    "MaxSimScorer",
    "MemoryCallback",
    "MemoryConsolidator",
    "MemoryContextEnricher",
    "MemoryDecay",
    "MemoryEntry",
    "MemoryEntryStore",
    "MemoryExtractor",
    "MemoryGarbageCollector",
    "MemoryManager",
    "MemoryOperation",
    "MemoryProvider",
    "MemoryQueryEnricher",
    "MemoryRetrieverAdapter",
    "MemoryType",
    "Message",
    "MetadataEnricher",
    "MetadataRouter",
    "MetricPoint",
    "MetricsCollector",
    "MODEL_PRICING",
    "ModalityEncoder",
    "ModelNotFoundError",
    "ModalityType",
    "MultiModalContent",
    "MultiModalConverter",
    "MultiModalItem",
    "MultiQueryTransformer",
    "OTLPMetricsExporter",
    "OTLPSpanExporter",
    "OpenAIFormatter",
    "OverflowStrategy",
    "PDFParser",
    "PairedEviction",
    "ParentChildChunker",
    "ParentExpander",
    "PipelineCallback",
    "PipelineDiagnostics",
    "PipelineEvaluator",
    "PipelineExecutionError",
    "PipelineStep",
    "PlainTextParser",
    "PostProcessor",
    "ProviderError",
    "ProgressiveSummarizationMemory",
    "ProviderNotInstalledError",
    "QueryBundle",
    "QueryClassifier",
    "QueryEnricher",
    "QueryRouter",
    "QueryTransformPipeline",
    "QueryTransformer",
    "RAGEvaluator",
    "RAGMetrics",
    "RateLimitError",
    "RecencyScorer",
    "RecursiveCharacterChunker",
    "Reranker",
    "RerankerPipeline",
    "RetrievalEvaluator",
    "RetrievalMetrics",
    "RetrievalMetricsCalculator",
    "Retriever",
    "RetrieverError",
    "Role",
    "RoundRobinReranker",
    "RoutedRetriever",
    "ScoreReranker",
    "ScoredMemoryRetriever",
    "SemanticChunker",
    "SentenceChunker",
    "ServerError",
    "SharedSpaceRetriever",
    "SimilarityConsolidator",
    "SimpleGraphMemory",
    "Skill",
    "SkillRegistry",
    "SlidingWindowMemory",
    "SourceType",
    "Span",
    "SpanExporter",
    "SpanKind",
    "SparseRetriever",
    "StepBackTransformer",
    "StepDiagnostic",
    "StopReason",
    "StorageError",
    "StreamChunk",
    "StreamDelta",
    "StreamResult",
    "StreamUsage",
    "SummaryBufferMemory",
    "TableAwareChunker",
    "TableEncoder",
    "TableExtractor",
    "TierCompactor",
    "TextEncoder",
    "TiktokenCounter",
    "TimeoutError",
    "TokenBudget",
    "TokenBudgetExceededError",
    "TokenLevelEncoder",
    "Tokenizer",
    "ToolCall",
    "ToolCallDelta",
    "ToolResult",
    "ToolSchema",
    "TraceRecord",
    "Tracer",
    "TracingCallback",
    "Usage",
    "VectorStore",
    "async_postprocessor_step",
    "async_reranker_step",
    "async_retriever_step",
    "auto_promotion_step",
    "calculate_cost",
    "classified_retriever_step",
    "create_eviction_promoter",
    "create_provider",
    "default_agent_budget",
    "default_chat_budget",
    "default_rag_budget",
    "extract_chunk_metadata",
    "filter_step",
    "generate_chunk_id",
    "generate_doc_id",
    "graph_retrieval_step",
    "memory_skill",
    "memory_tools",
    "postprocessor_step",
    "query_transform_step",
    "rag_skill",
    "rag_tools",
    "register_provider",
    "reranker_step",
    "retriever_step",
    "rrf_fuse",
    "tool",
]

# MCP Bridge (optional — requires pip install astro-anchor[mcp])
try:
    import fastmcp as _fastmcp  # noqa: F401 — probe for optional dependency
except ImportError:
    pass  # fastmcp not installed — MCP bridge unavailable
else:
    from anchor.mcp import (
        FastMCPClientBridge,
        FastMCPServerBridge,
        MCPClient,
        MCPClientPool,
        MCPConfigError,
        MCPConnectionError,
        MCPError,
        MCPPrompt,
        MCPPromptArgument,
        MCPResource,
        MCPServer,
        MCPServerConfig,
        MCPTimeoutError,
        MCPToolError,
    )

    __all__ += [
        "FastMCPClientBridge",
        "FastMCPServerBridge",
        "MCPClient",
        "MCPClientPool",
        "MCPConfigError",
        "MCPConnectionError",
        "MCPError",
        "MCPPrompt",
        "MCPPromptArgument",
        "MCPResource",
        "MCPServer",
        "MCPServerConfig",
        "MCPTimeoutError",
        "MCPToolError",
    ]
